apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxy-orderer-example-com-claim0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
status: {}
